/**
 * generated by Xtext
 */
package org.spp.cocome.behavior.validation;

import org.spp.cocome.behavior.validation.AbstractBehaviorValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class BehaviorValidator extends AbstractBehaviorValidator {
}
