/*
 * generated by Xtext
 */
package org.spp.cocome.behavior;

import org.eclipse.xtext.naming.IQualifiedNameConverter;
import org.spp.cocome.behavior.pcm.handler.PCMModelGlobalScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BehaviorRuntimeModule extends org.spp.cocome.behavior.AbstractBehaviorRuntimeModule {
	/**
	 * {@inheritDoc}<br>
	 * This extension registers the custom {@link PCMModelGlobalScopeProvider} that realizes e.g. the
	 * correct linking of PCM mapping types. The implementation of that part is broadly transfered
	 * from the JVMTypes binding.
	 */
	@Override
	public Class<? extends org.eclipse.xtext.scoping.IGlobalScopeProvider> bindIGlobalScopeProvider() {
		return PCMModelGlobalScopeProvider.class;
	}
	
	/**
	 * Use the XtextQualifiedNameConverter to support URIs??
	 * @return
	 */
	public Class<? extends IQualifiedNameConverter> bindIQualifiedNameConverter() {
		return IQualifiedNameConverter.DefaultImpl.class;
	}
}
