/*
* generated by Xtext
*/
package org.spp.cocome.behavior;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class BehaviorStandaloneSetup extends BehaviorStandaloneSetupGenerated{

	public static void doSetup() {
		new BehaviorStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

