/*
 * generated by Xtext
 */
package org.spp.cocome.behavior.ui.contentassist

import org.spp.cocome.behavior.ui.contentassist.AbstractBehaviorProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class BehaviorProposalProvider extends AbstractBehaviorProposalProvider {
}
