/*
* generated by Xtext
*/
package org.spp.cocome.behavior.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.spp.cocome.behavior.services.BehaviorGrammarAccess;

public class BehaviorParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private BehaviorGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.spp.cocome.behavior.parser.antlr.internal.InternalBehaviorParser createParser(XtextTokenStream stream) {
		return new org.spp.cocome.behavior.parser.antlr.internal.InternalBehaviorParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "BehaviorModel";
	}
	
	public BehaviorGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(BehaviorGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
