/*
 * generated by Xtext
 */
package org.spp.cocome.behavior.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BehaviorUiModule extends org.spp.cocome.behavior.ui.AbstractBehaviorUiModule {
	public BehaviorUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
