/*
 * generated by Xtext
 */
package org.spp.cocome.behavior.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.spp.cocome.behavior.ui.internal.BehaviorActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BehaviorExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return BehaviorActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return BehaviorActivator.getInstance().getInjector(BehaviorActivator.ORG_SPP_COCOME_BEHAVIOR_BEHAVIOR);
	}
	
}
